version: '3'

services:
  db:
    image: lucasvscn/nodedb
    build:
      context: mysql
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
    networks:
      - node-network

  app:
    image: lucasvscn/nodeapp
    build:
      context: node
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s dockerize -wait tcp://db:3306 npm start
    tty: true
    volumes:
      - ./node/app:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db
      - proxy

  proxy:
    image: lucasvscn/nodeproxy
    build:
      context: nginx
    container_name: proxy
    restart: always
    ports:
      - 8080:8080
    networks:
      - node-network

networks:
  node-network:
    driver: bridge