version: '3'

services:
  db:
    image: lucasvscn/nodedb
    build:
      context: mysql
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    ports:
      - 3000:3000
    networks:
      - node-network
    depends_on:
      - db

networks:
  node-network:
    driver: bridge