INSERT INTO `people` (`name`) VALUES ('Light Yagami');
INSERT INTO `people` (`name`) VALUES ('Kiyomi Takada');
INSERT INTO `people` (`name`) VALUES ('Rem');
INSERT INTO `people` (`name`) VALUES ('Watari');
INSERT INTO `people` (`name`) VALUES ('Matt');
INSERT INTO `people` (`name`) VALUES ('Mello');
INSERT INTO `people` (`name`) VALUES ('Raye Penber');
INSERT INTO `people` (`name`) VALUES ('Soichiro Yagami');
INSERT INTO `people` (`name`) VALUES ('Naomi Misora');
INSERT INTO `people` (`name`) VALUES ('L');